# Set up for GitHub Actions, npm and Composer

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
    - "dependencies"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      interval: "monthly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    labels:
    - "dependencies"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      interval: "monthly"
    target-branch: "develop"
    versioning-strategy: increase

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    allow:
    - dependency-type: direct
    - dependency-type: indirect
    directory: "/"
    labels:
    - "dependencies"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      interval: "monthly"
    target-branch: "develop"
    versioning-strategy: increase
